name: Publish npm package
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npx playwright install
      - run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm clean-install
      - run: npm publish --access public
        env:
          # actions/setup-node uses this env variable to set the auth token in the .npmrc file
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
